<?php

namespace AppBundle\Repository;

/**
 * AddresseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddresseeRepository extends \Doctrine\ORM\EntityRepository
{
}
