<?php

namespace AppBundle\Repository;

/**
 * GiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftRepository extends \Doctrine\ORM\EntityRepository
{
}
