<?php

namespace AppBundle\Repository;

/**
 * UserConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
