# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.gift:
        class: AppBundle\Admin\GiftAdmin
        arguments: [~, AppBundle\Entity\Gift, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Gifts }
    admin.buyer:
        class: AppBundle\Admin\BuyerAdmin
        arguments: [~, AppBundle\Entity\Buyer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Buyers }
        calls:
            - [ setTemplate, [edit, :Admin:edit_buyer.html.twig]]
    admin.payment:
        class: AppBundle\Admin\PaymentAdmin
        arguments: [~, AppBundle\Entity\Payment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Payments }
    admin.shop:
        class: AppBundle\Admin\ShopAdmin
        arguments: [~, AppBundle\Entity\Shop, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Shops }
