# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.gift:
        class: AppBundle\Admin\GiftAdmin
        arguments: [~, AppBundle\Entity\Gift, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Gifts }
